#!/usr/bin/env bash
# Start the local Smithers stack and expose it through an ngrok HTTPS tunnel.
#
# Keep this process running while a physical iPhone is using the preview URL.
# The script writes build-ready environment exports to:
#   build/preview-tunnel/smithers-preview.env

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GUI_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SMITHERS_CHECKOUT="${SMITHERS_CHECKOUT:-${PLUE_CHECKOUT:-$(cd "$GUI_ROOT/.." && pwd)/plue}}"
SMITHERS_PORT="${SMITHERS_PORT:-${PLUE_PORT:-4000}}"
LOCAL_SMITHERS_URL="http://localhost:${SMITHERS_PORT}"
NGROK_API_URL="${NGROK_API_URL:-http://127.0.0.1:4040}"
STATE_DIR="${SMITHERS_PREVIEW_STATE_DIR:-${PLUE_PREVIEW_STATE_DIR:-$GUI_ROOT/build/preview-tunnel}}"
ENV_FILE="${SMITHERS_PREVIEW_ENV_FILE:-${PLUE_PREVIEW_ENV_FILE:-$STATE_DIR/smithers-preview.env}}"
NGROK_LOG="$STATE_DIR/ngrok.log"
NGROK_PID_FILE="$STATE_DIR/ngrok.pid"
STARTED_NGROK_PID=""
PUBLIC_URL=""

log() { echo "[preview-tunnel] $*" >&2; }

die() {
    echo "[preview-tunnel] FAIL: $*" >&2
    exit 2
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "$1 is required"
}

trim_base_url() {
    local value="$1"
    while [[ "$value" == */ ]]; do
        value="${value%/}"
    done
    if [[ "$value" == */api ]]; then
        value="${value%/api}"
    fi
    printf '%s\n' "$value"
}

health_status() {
    local base="$1"
    curl -sS --connect-timeout 2 --max-time 5 -o /dev/null -w '%{http_code}' \
        "$(trim_base_url "$base")/api/health" 2>/dev/null || true
}

wait_for_smithers() {
    local base="$1"
    local deadline=$((SECONDS + 180))
    local status=""

    until [[ "$status" == "200" ]]; do
        status="$(health_status "$base")"
        if (( SECONDS >= deadline )); then
            die "Smithers API did not become reachable at $(trim_base_url "$base")/api/health"
        fi
        sleep 2
    done
}

ensure_smithers_stack() {
    [[ -d "$SMITHERS_CHECKOUT" ]] || die "Smithers backend checkout not found at $SMITHERS_CHECKOUT"

    if [[ "$(health_status "$LOCAL_SMITHERS_URL")" == "200" ]]; then
        log "Smithers API already reachable at $LOCAL_SMITHERS_URL"
        return
    fi

    log "starting Smithers docker stack in $SMITHERS_CHECKOUT"
    (cd "$SMITHERS_CHECKOUT" && make docker-up)
    log "waiting for Smithers API on $LOCAL_SMITHERS_URL"
    wait_for_smithers "$LOCAL_SMITHERS_URL"
    log "Smithers API reachable"
}

ngrok_public_url() {
    curl -sS --connect-timeout 2 --max-time 5 "$NGROK_API_URL/api/tunnels" 2>/dev/null \
        | /usr/bin/python3 -c '
import json
import sys

port = sys.argv[1]
try:
    payload = json.load(sys.stdin)
except Exception:
    sys.exit(0)

fallback = ""
for tunnel in payload.get("tunnels", []):
    public_url = tunnel.get("public_url", "")
    if not public_url.startswith("https://"):
        continue
    addr = str(tunnel.get("config", {}).get("addr", ""))
    if port in addr:
        print(public_url)
        sys.exit(0)
    if not fallback:
        fallback = public_url

if fallback:
    print(fallback)
' "$SMITHERS_PORT" 2>/dev/null || true
}

start_ngrok() {
    local url=""
    url="$(ngrok_public_url)"
    if [[ -n "$url" ]]; then
        log "reusing existing ngrok tunnel: $url"
        PUBLIC_URL="$url"
        return
    fi

    if [[ -f "$NGROK_PID_FILE" ]]; then
        local old_pid
        old_pid="$(cat "$NGROK_PID_FILE" 2>/dev/null || true)"
        if [[ -n "$old_pid" ]] && ! kill -0 "$old_pid" 2>/dev/null; then
            rm -f "$NGROK_PID_FILE"
        fi
    fi

    : > "$NGROK_LOG"
    log "starting ngrok tunnel for localhost:$SMITHERS_PORT"
    ngrok http "$SMITHERS_PORT" --log=stdout >"$NGROK_LOG" 2>&1 &
    STARTED_NGROK_PID="$!"
    echo "$STARTED_NGROK_PID" > "$NGROK_PID_FILE"

    local deadline=$((SECONDS + 30))
    until [[ -n "$url" ]]; do
        if ! kill -0 "$STARTED_NGROK_PID" 2>/dev/null; then
            explain_ngrok_failure
        fi
        url="$(ngrok_public_url)"
        if (( SECONDS >= deadline )); then
            explain_ngrok_failure "timed out waiting for ngrok public URL from $NGROK_API_URL"
        fi
        sleep 1
    done

    PUBLIC_URL="$url"
}

explain_ngrok_failure() {
    local fallback="${1:-ngrok exited before publishing a tunnel}"
    tail -40 "$NGROK_LOG" >&2 || true
    if grep -q "ERR_NGROK_4018" "$NGROK_LOG" 2>/dev/null; then
        die "ngrok is installed but not authenticated; run 'ngrok config add-authtoken <token>' once, then rerun this script"
    fi
    die "$fallback"
}

shell_quote() {
    local value="$1"
    printf "'%s'" "${value//\'/\'\\\'\'}"
}

write_env_file() {
    local url="$1"
    local quoted_url quoted_file
    quoted_url="$(shell_quote "$url")"
    quoted_file="$(shell_quote "$ENV_FILE")"

    cat > "$ENV_FILE" <<EOF
# Generated by ios/scripts/start-preview-tunnel.sh.
# Source this from another terminal while this tunnel process is running.
export SMITHERS_PREVIEW_URL=$quoted_url
export SMITHERS_BASE_URL=$quoted_url
export SMITHERS_PREVIEW_ENV_FILE=$quoted_file
export PLUE_PREVIEW_URL=$quoted_url
export PLUE_BASE_URL=$quoted_url
export PLUE_PREVIEW_ENV_FILE=$quoted_file
EOF
}

cleanup() {
    local rc=$?
    if [[ -n "$STARTED_NGROK_PID" ]] && kill -0 "$STARTED_NGROK_PID" 2>/dev/null; then
        log "stopping ngrok pid $STARTED_NGROK_PID"
        kill "$STARTED_NGROK_PID" 2>/dev/null || true
    fi
    exit "$rc"
}
trap cleanup INT TERM EXIT

main() {
    require_command curl
    require_command docker
    require_command ngrok
    require_command /usr/bin/python3

    mkdir -p "$STATE_DIR"
    ensure_smithers_stack

    local public_url
    start_ngrok
    public_url="$(trim_base_url "$PUBLIC_URL")"
    export SMITHERS_PREVIEW_URL="$public_url"
    export SMITHERS_BASE_URL="$public_url"
    export PLUE_PREVIEW_URL="$public_url"
    export PLUE_BASE_URL="$public_url"
    write_env_file "$public_url"

    cat <<EOF

Smithers preview tunnel is ready.

  SMITHERS_PREVIEW_URL=$SMITHERS_PREVIEW_URL
  SMITHERS_BASE_URL=$SMITHERS_BASE_URL
  Local health:  $LOCAL_SMITHERS_URL/api/health
  Tunnel health: $SMITHERS_PREVIEW_URL/api/health
  Env file:      $ENV_FILE

In another terminal, build for a physical device with:

  cd $(shell_quote "$GUI_ROOT")
  source $(shell_quote "$ENV_FILE")
  ./ios/scripts/build-for-device.sh

OAuth2 still redirects to smithers://oauth2/callback; the app derives the
backend base URL from the baked SMITHERS_BASE_URL / SMITHERS_PREVIEW_URL value.

Press Ctrl-C here to stop the tunnel.
EOF

    if [[ -n "$STARTED_NGROK_PID" ]]; then
        wait "$STARTED_NGROK_PID"
    else
        while true; do sleep 3600; done
    fi
}

main "$@"
